### ISSUE TITLE
Create server folder structure

### ISSUE THREAD

**Issue by Any28Flo** [ayushagg31/Trellis#6]
I think we could create a server folder and inside it, save the config server, the middlewares, the routes, the schemas

**Comment by ayushagg31** [comment]
I started this project with the similar structure, you can see it [here](https://github.com/ayushagg31/Trellis/tree/d7a781a82dfb3c02637da096a57932cacd46f6bc), but during deployment phase I was getting a lot of build errors due to this, so had to destructure the server folder and move out all these files to the root of the project. Let me know, if you are intersted it give it a try, I'll be happy to help.

**Comment by Any28Flo** [comment]
Do you have hosted your api? where? Please, share with me the URL. If not, what do you think about host in [mLab](https://mlab.com/) or[mongoAtlas](https://mlab.com/)
The deploy, Where do you do you made de deploy, Heroku or Netlify?

**Comment by ayushagg31** [comment]
This application is hosted on Heroku and I am using MongoAtlas for maintaining the user data.

**Comment by ayushagg31** [comment]
Ping me on discord - **gozmit#3715**, if you have any further issue, I'll give you a walkthrough of whole project.
